# Generated by Django 2.0.5 on 2018-06-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problemandsolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemname', models.CharField(default='', max_length=150)),
                ('problemdetails', models.CharField(default='', max_length=500)),
                ('problemsignandsymptom', models.CharField(default='', max_length=500)),
                ('solution', models.CharField(default='', max_length=500)),
                ('youtubeurl', models.URLField(default='')),
            ],
        ),
    ]
